### ISSUE TITLE
Passwords in Generated XML file are wrong

### ISSUE THREAD

**Issue by shaverstudios** [myspoonistoobig/AtomicFire#2]
I tried this script with and without a password in my FireFTP .dat file. The exported XML file contains the proper passwords, but extra characters.

I had to open the XML file, and copy and paste the base64 encoded passwords into a decoder. Then I had to delete the extra characters (which showed as boxes with a question mark inside), then paste those correct passwords into FileZilla. After that it worked fine.

**Comment by myspoonistoobig** [comment]
I'll run some additional tests to see if I can reproduce what you're seeing. 

Can you give me a few extra details:
- Is it always the same number of extra characters?
- Is it always the same extra characters?
- What are you system details? I tested primarily on a Mac.

**Comment by shaverstudios** [comment]
After decoding, some passwords had just 1 extra character (box with question mark around it), while others had 3 or 4.

They are all boxes with question marks inside.

I am on Windows 10 64-bit.

Hope that helps! Thanks for the tool :)

**Comment by myspoonistoobig** [comment]
Thanks for finding the bug. This is corrected by https://github.com/myspoonistoobig/AtomicFire/commit/2d138a672bd7c837b56a889aea20a89b2815adbf

I was not removing padding added to strings for encryption after decrypting.
